//! Markdown policy report generation (req §16.4 Policy Report — could-have).

use crate::effective::EffectivePolicy;
use crate::model::Policy;
use crate::risk::RiskScore;

/// Render a shareable Markdown report of the effective policy + risk score.
pub fn markdown(
    project_name: &str,
    profile: Option<&str>,
    risk: &RiskScore,
    effective: &[EffectivePolicy],
) -> String {
    let mut allowed: Vec<&str> = Vec::new();
    let mut denied: Vec<&str> = Vec::new();
    let mut asked: Vec<&str> = Vec::new();
    let mut conflicts: Vec<&str> = Vec::new();
    for e in effective {
        match e.effective {
            Policy::Allow => allowed.push(&e.path),
            Policy::Deny => denied.push(&e.path),
            Policy::Ask => asked.push(&e.path),
        }
        if e.conflict {
            conflicts.push(&e.path);
        }
    }

    let mut out = String::new();
    out.push_str(&format!("# Agent Guard Policy Report — {project_name}\n\n"));
    out.push_str(&format!(
        "- Profile: **{}**\n- Risk score: **{} ({:?})**\n\n",
        profile.unwrap_or("—"),
        risk.score,
        risk.level
    ));

    let section = |out: &mut String, title: &str, icon: &str, items: &[&str]| {
        out.push_str(&format!("## {title}\n\n"));
        if items.is_empty() {
            out.push_str("_none_\n\n");
        } else {
            for p in items {
                out.push_str(&format!("- {icon} `{p}`\n"));
            }
            out.push('\n');
        }
    };

    section(&mut out, "Allowed", "✅", &allowed);
    section(&mut out, "Denied", "⛔", &denied);
    section(&mut out, "Ask", "❓", &asked);
    if !conflicts.is_empty() {
        section(&mut out, "Conflicts (deny wins)", "⚠️", &conflicts);
    }
    out.push_str("---\n_Generated by Agent Guard._\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::effective::EffectivePolicy;
    use crate::model::{Policy, Scope};
    use crate::risk::RiskScore;

    #[test]
    fn renders_sections() {
        let eff = vec![
            EffectivePolicy {
                path: "src".into(),
                effective: Policy::Allow,
                source_scope: Some(Scope::Project),
                explicit: true,
                conflict: false,
            },
            EffectivePolicy {
                path: "secrets".into(),
                effective: Policy::Deny,
                source_scope: Some(Scope::Project),
                explicit: true,
                conflict: false,
            },
        ];
        let md = markdown(
            "proj",
            Some("Conservative"),
            &RiskScore {
                score: 80,
                level: crate::model::RiskLevel::High,
            },
            &eff,
        );
        assert!(md.contains("# Agent Guard Policy Report — proj"));
        assert!(md.contains("✅ `src`"));
        assert!(md.contains("⛔ `secrets`"));
        assert!(md.contains("Conservative"));
    }
}
